version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aqsweb-windows
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Configuraciones específicas para Windows
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - aqsweb-windows-network

networks:
  aqsweb-windows-network:
    driver: bridge

